apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ylitalot
  namespace: kube-system
spec:
  secretName: wildcard-ylitalot-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - ylitalot.com
    - "*.ylitalot.com"
